version: "3.8"

services:
  
  database:
    image: mongo
    volumes:
      - mongodb_data:/data/db
    env_file:
     - ./env/mongo.env
    ports:
      - 27017:27017
    container_name: mongodb

  frontend:
    stdin_open: true
    tty: true
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    depends_on: 
      - backend
    container_name: frontend
  
  backend:
    build: ./backend
      #context: ./backend
      #dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8000:8000
    env_file:
      - ./env/backend.env
    depends_on:
      - database
    container_name: backend

volumes:
  mongodb_data: